/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuRegistrarIngreso = new javax.swing.JMenuItem();
        menuRegistrarSalida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuVisitantesActuales = new javax.swing.JMenuItem();
        menuHistorialVisitantes = new javax.swing.JMenuItem();
        menuVisitantesOficina = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ramo");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ramo_logo_2.png"))); // NOI18N

        jMenu1.setText("Visitas");

        menuRegistrarIngreso.setText("Registrar Ingreso");
        menuRegistrarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarIngresoActionPerformed(evt);
            }
        });
        jMenu1.add(menuRegistrarIngreso);

        menuRegistrarSalida.setText("Registrar Salida");
        menuRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarSalidaActionPerformed(evt);
            }
        });
        jMenu1.add(menuRegistrarSalida);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        menuVisitantesActuales.setText("Visitantes Actuales");
        menuVisitantesActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVisitantesActualesActionPerformed(evt);
            }
        });
        jMenu2.add(menuVisitantesActuales);

        menuHistorialVisitantes.setText("Historial de Visitantes");
        menuHistorialVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistorialVisitantesActionPerformed(evt);
            }
        });
        jMenu2.add(menuHistorialVisitantes);

        menuVisitantesOficina.setText("Visitantes por Oficina");
        menuVisitantesOficina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVisitantesOficinaActionPerformed(evt);
            }
        });
        jMenu2.add(menuVisitantesOficina);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        menuSalir.setText("Salir de la Aplicación");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu3.add(menuSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistrarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarIngresoActionPerformed
        // TODO add your handling code here:
        FrmRegistrarIngreso frm = new FrmRegistrarIngreso();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuRegistrarIngresoActionPerformed

    private void menuVisitantesActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVisitantesActualesActionPerformed
        // TODO add your handling code here:
        FrmVisitasActuales frm = new FrmVisitasActuales();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuVisitantesActualesActionPerformed

    private void menuRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarSalidaActionPerformed
        // TODO add your handling code here:
        FrmRegistrarSalida frm = new FrmRegistrarSalida();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuRegistrarSalidaActionPerformed

    private void menuHistorialVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistorialVisitantesActionPerformed
        // TODO add your handling code here:
        FrmHistorialVisitas frm = new FrmHistorialVisitas();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuHistorialVisitantesActionPerformed

    private void menuVisitantesOficinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVisitantesOficinaActionPerformed
        // TODO add your handling code here:
        FrmVisitasOficinas frm = new FrmVisitasOficinas();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuVisitantesOficinaActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        int salir = JOptionPane.showConfirmDialog(null, "Esta seguro que quiere salir?");
        if (salir == 0) {;
            FrmInicioSesion frm = new FrmInicioSesion();
            frm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuHistorialVisitantes;
    private javax.swing.JMenuItem menuRegistrarIngreso;
    private javax.swing.JMenuItem menuRegistrarSalida;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuVisitantesActuales;
    private javax.swing.JMenuItem menuVisitantesOficina;
    // End of variables declaration//GEN-END:variables
}
